theme: jekyll-theme-hacker
# Site settings
title: MathHome    				  	#你博客的标题
SEOTitle: YXQ666    	 #显示在浏览器上搜索的时候显示的标题
#header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: manage@em.yxqweb.men	
description: "MathHome"  			 #网站介绍
keyword: "MathHome," #关键词
url: "https://yxqweb.men"          # 这个就是填写你的博客地址
#baseurl: ""      # 这个我们不用填写
